export const AllLanguageFromJson = [
  { Language: "English", Native: "English", BCP47: "en" },
  { Language: "Afrikaans", Native: "Afrikaans", BCP47: "af" },
  { Language: "German", Native: "Deutsch", BCP47: "de-DE" },
  { Language: "Hindi", Native: "हिंदी", BCP47: "hi" },
];
// export const AllLanguageFromJson = [
//     {"Language": "English", "Native": "English", "BCP47": "en" },
//     {"Language": "Afrikaans","Native": "Afrikaans", "BCP47": "af" },
//     {"Language": "Albanian","Native": "Shqiptare", "BCP47": "sq" },
//     {"Language": "Aymara","Native": "Aymara aru", "BCP47": "ay" },
//     {"Language": "Azerbaijani","Native": "Azərbaycan dili", "BCP47": "az" },
//     {"Language": "Bambara","Native": "Bambara", "BCP47": "bm" },
//     {"Language": "Basque","Native": "Euskara", "BCP47": "eu" },
//     {"Language": "Bosnian","Native": "Bosanski", "BCP47": "bs" },
//     {"Language": "Catalan","Native": "català", "BCP47": "ca" },
//     {"Language": "Cebuano","Native": "Cebuano", "BCP47": "ceb" },
//     {"Language": "Corsican","Native": "corsu", "BCP47": "co" },
//     {"Language": "Croatian","Native": "Hrvatski", "BCP47": "hr" },
//     {"Language": "Czech","Native": "čeština", "BCP47": "cs" },
//     {"Language": "Danish","Native": "Dansk", "BCP47": "da" },
//     {"Language": "Dutch","Native": "Nederlands", "BCP47": "nl-NL" },
//     {"Language": "Esperanto","Native": "esperanto", "BCP47": "eo" },
//     {"Language": "Estonian","Native": "eesti keel", "BCP47": "et" },
//     {"Language": "Ewe","Native": "Eʋegbe", "BCP47": "ee" },
//     {"Language": "Filipino (Tagalog)","Native": "Filipino", "BCP47": "fil" },
//     {"Language": "Finnish","Native": "Suomen kieli", "BCP47": "fi" },
//     {"Language": "French","Native": "Français", "BCP47": "fr-FR" },
//     {"Language": "Frisian","Native": "Frysk", "BCP47": "fy" },
//     {"Language": "Galician","Native": "Galego", "BCP47": "gl" },
//     {"Language": "German","Native": "Deutsch", "BCP47": "de-DE" },
//     {"Language": "Guarani","Native": "Guaran", "BCP47": "gn" },
//     {"Language": "Haitian Creole","Native": "Kreyòl ayisyen", "BCP47": "ht" },
//     {"Language": "Hausa","Native": "Hausa", "BCP47": "ha" },
//     {"Language": "Hawaiian","Native": "Ōlelo Hawaiʻi", "BCP47": "haw" },
//     {"Language": "Hmong","Native": "Hmoob", "BCP47": "hmn" },
//     {"Language": "Hungarian","Native": "Magyar", "BCP47": "hu" },
//     {"Language": "Icelandic","Native": "íslenskur", "BCP47": "is" },
//     {"Language": "Igbo","Native": "Igbo", "BCP47": "ig" },
//     {"Language": "Ilocano","Native": "Ilocano", "BCP47": "ilo" },
//     {"Language": "Indonesian","Native": "Bahasa Indo", "BCP47": "id-ID" },
//     {"Language": "Irish","Native": "Gaeilge", "BCP47": "ga" },
//     {"Language": "Italian","Native": "Italiano", "BCP47": "it-IT" },
//     {"Language": "Javanese","Native": "Basa Jawa", "BCP47": "jv" },
//     {"Language": "Kinyarwanda","Native": "Kinyarwanda", "BCP47": "rw" },
//     {"Language": "Krio","Native": "Krio", "BCP47": "kri" },
//     {"Language": "Kurdish","Native": "Kurdî", "BCP47": "ku" },
//     {"Language":"Latin","Native": "Latinus", "BCP47": "la" },
//     {"Language": "Latvian","Native": "Latviski", "BCP47": "lv" },
//     {"Language": "Lingala","Native": "Lingála", "BCP47": "ln" },
//     {"Language": "Lithuanian","Native": "Lietuvių", "BCP47": "lt" },
//     {"Language": "Luganda","Native": "Oluganda", "BCP47": "lg" },
//     {"Language": "Luxembourgish", "Native": "Lëtzebuergesch", "BCP47": "lb" },
//     {"Language": "Malagasy","Native": "fiteny malagasy", "BCP47": "mg" },
//     {"Language": "Malay","Native": "Melayu", "BCP47": "ms" },
//     {"Language": "Maltese","Native": "Malti", "BCP47": "mt" },
//     {"Language": "Maori","Native": "Māori", "BCP47": "mi" },
//     {"Language": "Mizo", "Native": "Mizo", "BCP47": "lus" },
//     {"Language": "Norwegian","Native": "Norsk", "BCP47": "no-NO" },
//     {"Language": "Oromo","Native": "Afaan Oromoo", "BCP47": "om" },
//     {"Language": "Polish","Native": "Polski", "BCP47": "pl" },
//     {"Language": "Portuguese","Native": "Portugalski ", "BCP47": "pt-PT" },
//     {"Language": "Quechua","Native": "Runasimi", "BCP47": "qu" },
//     {"Language": "Romanian","Native": "Românesc", "BCP47": "ro-RO" },
//     {"Language": "Samoan","Native": "Samoa", "BCP47": "sm" },
//     {"Language": "Scots Gaelic","Native": "Gàidhlig na h-Alba", "BCP47": "gd" },
//     {"Language": "Sepedi","Native": "Sepedi", "BCP47": "nso" },
//     {"Language": "Sesotho","Native": "seSotho", "BCP47": "st" },
//     {"Language": "Shona","Native": "Shona", "BCP47": "sn" },
//     {"Language": "Slovak","Native": "Slovenský", "BCP47": "sk" },
//     {"Language": "Slovenian","Native": "Slovenščina", "BCP47": "sl" },
//     {"Language": "Somali","Native": "Soomaali", "BCP47": "so" },
//     {"Language": "Spanish","Native": "Español", "BCP47": "es-ES" },
//     {"Language": "Sundanese","Native": "basa Sunda", "BCP47": "su" },
//     {"Language": "Swahili","Native": "kiswahili", "BCP47": "sw" },
//     {"Language": "Swedish","Native": "Svenska", "BCP47": "sv-SE" },
//     {"Language": "Tagalog (Filipino)","Native": "Filipino (Tagalog)", "BCP47": "tl" },
//     {"Language": "Tsonga","Native": "Tsonga", "BCP47": "ts" },
//     {"Language": "Turkish","Native": "Türkçe", "BCP47": "tr" },
//     {"Language": "Turkmen","Native": "Türkmenler", "BCP47": "tk" },
//     {"Language": "Twi (Akan)","Native": "Twi", "BCP47": "ak" },
//     {"Language": "Uzbek","Native": "o'zbek", "BCP47": "uz" },
//     {"Language": "Vietnamese","Native": "Tiếng Việt", "BCP47": "vi" },
//     {"Language": "Welsh","Native": "Cymraeg", "BCP47": "cy" },
//     {"Language": "Xhosa","Native": "isiXhosa", "BCP47": "xh" },
//     {"Language": "Yoruba","Native": "Yoruba", "BCP47": "yo" },
//     {"Language": "Zulu","Native": "isiZulu", "BCP47": "zu" },
//     {"Language": "Belarusian","Native": "беларускі", "BCP47": "be" },
//     {"Language": "Bulgarian","Native": "български", "BCP47": "bg" },
//     {"Language": "Kazakh","Native": "қазақ", "BCP47": "kk" },
//     {"Language": "Kyrgyz","Native": "Кыргызча", "BCP47": "ky" },
//     {"Language": "Macedonian","Native": "македонски", "BCP47": "mk" },
//     {"Language": "Mongolian","Native": "Монгол", "BCP47": "mn" },
//     {"Language": "Russian","Native": "Русский", "BCP47": "ru-RU" },
//     {"Language": "Serbian","Native": "Српски", "BCP47": "sr" },
//     {"Language": "Tajik","Native": "тоҷикӣ", "BCP47": "tg" },
//     {"Language": "Tatar","Native": "Татар", "BCP47": "tt" },
//     {"Language": "Ukrainian","Native": "українська", "BCP47": "uk" },
//     {"Language": "Konkani","Native": "कोंकणी", "BCP47": "gom" },
//     {"Language": "Maithili","Native": "मैथिली", "BCP47": "mai" },
//     {"Language": "Marathi","Native": "मराठी", "BCP47": "mr" },
//     {"Language": "Chichewa","Native": "चिचेवा", "BCP47": "ny" },
//     {"Language": "Sanskrit","Native": "संस्कृत", "BCP47": "sa" },
//     {"Language": "Dogri","Native": "डोगरी", "BCP47": "doi" },
//     {"Language": "Hindi","Native": "हिंदी", "BCP47": "hi" },
//     {"Language": "Nepali","Native": "नेपाली", "BCP47": "ne" },
//     {"Language": "Pashto","Native": "پښتو", "BCP47": "ps" },
//     {"Language": "Persian","Native": "فارسی", "BCP47": "fa" },
//     {"Language": "Urdu","Native": "اردو", "BCP47": "ur" },
//     {"Language": "Arabic","Native": " عربي", "BCP47": "ar-SA" },
//     {"Language": "Uyghur","Native": "ئۇيغۇر", "BCP47": "ug" },
//     {"Language": "Assamese","Native": "অসমীয়া", "BCP47": "as" },
//     {"Language": "Bengali","Native": "বাংলা", "BCP47": "bn-BD" },
//     {"Language": "Hebrew","Native": "עִברִית", "BCP47": "he" },
//     {"Language": "Yiddish","Native": "יידיש", "BCP47": "yi" },
//     {"Language": "Armenian","Native": "հայերեն", "BCP47": "hy" },
//     {"Language": "Burmese","Native": "မြန်မာ", "BCP47": "my" },
//     {"Language": "Amharic","Native": "አማርኛ", "BCP47": "am" },
//     {"Language": "Tigrinya","Native": "ትግሪኛ", "BCP47": "ti" },
//     {"Language": "Georgian","Native": "ქართული", "BCP47": "ka" },
//     {"Language": "Greek","Native": "Έλληνες", "BCP47": "el-GR" },
//     {"Language": "Punjabi","Native": " ਪੰਜਾਬੀ", "BCP47": "pa" },
//     {"Language": "Mandarin Chinese","Native": "国语", "BCP47": "zh-CN" },
//     {"Language": "Chinese (Traditional)","Native":"中國傳統的）", "BCP47": "zh-TW" },
//     {"Language": "Korean","Native": "한국인", "BCP47": "ko" },
//     {"Language": "Japanese","Native": "日本", "BCP47": "ja" },
//     {"Language": "Bhojpuri","Native": "भोजपुरी", "BCP47": "bho" },
//     {"Language": "Kannada","Native": "ಕನ್ನಡ", "BCP47": "kn" },
//     {"Language": "Khmer","Native": "ខ្មែរ", "BCP47": "km" },
//     {"Language": "Kurdish (Sorani)","Native": "کوردی","BCP47": "ckb" },
//     {"Language": "Lao","Native": "ພາສາລາວ", "BCP47": "lo" },
//     {"Language": "Malayalam","Native": "മലയാളം", "BCP47": "ml" },
//     {"Language": "Odia (Oriya)","Native": "ଓଡିଆ ଭାଷା", "BCP47": "or" },
//     {"Language": "Sindhi","Native": "سنڌي", "BCP47": "sd" },
//     {"Language": "Sinhala (Sinhalese)","Native": "සිංහල", "BCP47": "si" },
//     {"Language": "Gujarati","Native": "ગુજરાતીc" ,"BCP47": "gu" },
//     {"Language": "Tamil","Native": "தமிழ்", "BCP47": "ta" },
//     {"Language": "Telugu","Native": "తెలుగు", "BCP47": "te" },
//     {"Language": "Dhivehi","Native": "ދިވެހި,  ", "BCP47": "dv" },
//     {"Language": "Thai","Native": "แบบไทย", "BCP47": "th" },]

export const MickSupportedLanguage = [
  "en-US",
  "zh-CN",
  "es-ES",
  "ar-SA",
  "ru-RU",
  "bn-BD",
  "pt-PT",
  "id-ID",
  "fr-FR",
  "af",
  "eu",
  "ca",
  "ar-SA",
  "cs",
  "nl-NL",
  "fi",
  "gl",
  "de-DE",
  "el-GR",
  "he",
  "hu",
  "is",
  "it-IT",
  "ja",
  "ko",
  "la",
  "no-NO",
  "pl",
  "ro-RO",
  "sr-SP",
  "sk",
  "sv-SE",
  "tr",
  "zu",
];
